<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>14.0</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <RootNamespace>OfxSharpLib</RootNamespace>
    <AssemblyName>OfxSharpLib</AssemblyName>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageId>ejsilva.OfxSharpLib</PackageId>
    <Title>OfxSharpLib</Title>
    <Version>8.9.4</Version>
    <Authors>Afonso França, Antônio Milesi Bastos, James Hollingworth</Authors>
    <Copyright>MIT</Copyright>
    <PackageProjectUrl>https://github.com/EvertonJSilva/OfxSharp</PackageProjectUrl>
    <RepositoryUrl>https://github.com/EvertonJSilva/OfxSharp</RepositoryUrl>
    <PackageReleaseNotes>Convertido para versão .net core 8</PackageReleaseNotes>
    <Description>Versão .net core 8 do pacote OfxSharpLib</Description>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="SgmlReaderDll">
      <HintPath>..\packages\SgmlReader.1.8.11\lib\4.0\SgmlReaderDll.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Include="..\LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="ModelDiagram.cd" />
    <None Include="OfxSharp.nuspec" />
    <None Include="packages.config" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Xml.SgmlReader" Version="1.8.30" />
  </ItemGroup>

</Project>
